name: flutter_fbx3d_viewer
description: Flutter package for viewing Fbx 3d animated files with textures, basic lights, colors.
version: 1.0.0
homepage: https://github.com/klaszlo8207/Flutter-FBX-3D-Viewer

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  vector_math: ^2.0.8
  provider: ^5.0.0
  archive: ^3.1.2
  image: ^3.0.2

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  #assets:
  #- assets/knight.fbx
